### ISSUE TITLE
Adding article's Tags  - request

### ISSUE THREAD

**Issue by MortezaAghili** [Massad/gin-boilerplate#13]
I wanna use your great boilerplate, but because I'm a newbie Golang developer I have a request, can you please add Tags relationship for the articles. I wanna see how can I implement such things for my demo Restful APIs.

**Comment by Massad** [comment]
@MortezaAghili if you take a look at this query: https://github.com/Massad/gin-boilerplate/blob/master/models/article.go#L37 it holds multiple tricks as an advanced example for the PostgreSQL.

And as for this request, I'm sorry but as you mentioned this is a boilerplate to kickstart a project and tags is a custom thing. However, you can check the relation between the **article** and **user** in that query as well so you can do the same with "tags".
