### ISSUE TITLE
just a question

### ISSUE THREAD

**Issue by anvk** [Massad/gin-boilerplate#3]
Probably a very basic and stupid question - but what is the main purpose of having forms and models? Why not to use just models?

**Comment by Massad** [comment]
@anvk separating (organising) things is always better for future. However, in Golang putting all the files in one file for example the `main.go` is the same as making many files and importing.

Also it helps making a short code in a single file and most important for not duplicating the code.

In my case, if i want to for example to edit all the forms, i know where to find them easily and that's the same for the team.
